// Action Types
// Authentication
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const RETRIVE_AUTHENTICATION_REQUEST = 'RETRIVE_AUTHENTICATION_REQUEST'
export const RETRIVE_AUTHENTICATION_SUCCESS = 'RETRIVE_AUTHENTICATION_SUCCESS'

// Logout 
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

